version: '3.8'
services:
    react:
        build:
            context: ./
        ports:
            - '3000:5173'
        volumes:
            - ./:/app
            - /app/node_modules
        stdin_open: true
        tty: true
